/*
 * generated by Xtext
 */
package ch.trick17.peppl.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PepplUiModule extends ch.trick17.peppl.lang.ui.AbstractPepplUiModule {
	public PepplUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
