/*
 * generated by Xtext
 */
package ch.trick17.rolez.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RolezUiModule extends ch.trick17.rolez.lang.ui.AbstractRolezUiModule {
	public RolezUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
