language: java

jdk:
  - openjdk7

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xvfb

env:
  - MAVEN_OPTS="-Xmx1g -XX:MaxPermSize=512m"

install: xvfb-run mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: xvfb-run mvn install -B