/*
 * generated by Xtext
 */
package ch.trick17.rolez.lang;

import ch.trick17.rolez.lang.RolezStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RolezStandaloneSetup extends RolezStandaloneSetupGenerated{

	public static void doSetup() {
		new RolezStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

