/*
 * generated by Xtext
 */
package ch.trick17.peppl.lang;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PepplStandaloneSetup extends PepplStandaloneSetupGenerated{

	public static void doSetup() {
		new PepplStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

