/* generated by Xtext */
package ch.trick17.peppl.lang;

import ch.trick17.peppl.lang.typesystem.PepplStringRepresentation;
import it.xsemantics.runtime.StringRepresentation;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class PepplRuntimeModule extends AbstractPepplRuntimeModule {
    
    public Class<? extends StringRepresentation> bindStringRepresentation() {
        return PepplStringRepresentation.class;
    }
}
