/* generated by Xtext */
package ch.trick17.peppl.lang;

import com.google.inject.Binder;
import com.google.inject.name.Names;

import ch.trick17.peppl.lang.scoping.PepplImportedNamespaceScopeProvider;
import ch.trick17.peppl.lang.typesystem.PepplStringRepresentation;
import it.xsemantics.runtime.StringRepresentation;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class PepplRuntimeModule extends AbstractPepplRuntimeModule {
    
    public Class<? extends StringRepresentation> bindStringRepresentation() {
        return PepplStringRepresentation.class;
    }
    
    @Override
    public void configureIScopeProviderDelegate(Binder binder) {
        binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class).annotatedWith(Names.named(
                org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.NAMED_DELEGATE)).to(
                        PepplImportedNamespaceScopeProvider.class);
    }
}
