/* generated by Xtext */
package ch.trick17.peppl.lang;

import org.eclipse.xtext.naming.IQualifiedNameProvider;

import ch.trick17.peppl.lang.scoping.PepplNameProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class PepplRuntimeModule extends ch.trick17.peppl.lang.AbstractPepplRuntimeModule {
    
    @Override
    public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
        return PepplNameProvider.class;
    }
}
