/*
 * generated by Xtext
 */
package ch.trick17.rolez.lang.ui.contentassist

import ch.trick17.rolez.lang.ui.contentassist.AbstractRolezProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class RolezProposalProvider extends AbstractRolezProposalProvider {
}
