/**************************************************************************
 * * Java Grande Forum Benchmark Suite - Thread Version 1.0 * * produced by * *
 * Java Grande Benchmarking Project * * at * * Edinburgh Parallel Computing
 * Centre * * email: epcc-javagrande@epcc.ed.ac.uk * * Original version of this
 * code by Hon Yau (hwyau@epcc.ed.ac.uk) * * This version copyright (c) The
 * University of Edinburgh, 2001. * All rights reserved. * *
 **************************************************************************/

package section3.montecarlo;

/**
 * Class for defining the results of a task. Currently, this is simply the Monte
 * Carlo generate rate path.
 *
 * @author H W Yau
 * @version $Revision: 1.8 $ $Date: 1999/02/16 18:53:07 $
 */
public class ToResult implements java.io.Serializable {
    private final String header;
    private final double expectedReturnRate;
    private final double[] pathValue;
    
    /**
     * Constructor, for the results from a computation.
     *
     * @param header
     *            Simple header string.
     * @param expectedReturnRate expected return rate
     * @param pathValue
     *            Data computed by the Monte Carlo generator.
     */
    public ToResult(String header, double expectedReturnRate,
            double[] pathValue) {
        this.header = header;
        this.expectedReturnRate = expectedReturnRate;
        this.pathValue = pathValue;
    }
    
    /**
     * Gives a simple string representation of this object.
     *
     * @return String representation of this object.
     */
    @Override
    public String toString() {
        return(header);
    }
    
    // ------------------------------------------------------------------------
    // Accessor methods for class ToResult.
    // Generated by 'makeJavaAccessor.pl' script. HWY. 20th January 1999.
    // ------------------------------------------------------------------------
    
    /**
     * Accessor method for private instance variable
     * <code>expectedReturnRate</code>.
     *
     * @return Value of instance variable <code>expectedReturnRate</code>.
     */
    public double get_expectedReturnRate() {
        return(this.expectedReturnRate);
    }
    
    /**
     * Accessor method for private instance variable <code>pathValue</code>.
     *
     * @return Value of instance variable <code>pathValue</code>.
     */
    public double[] get_pathValue() {
        return(this.pathValue);
    }
    // ------------------------------------------------------------------------
}
